BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "secure-rpi"
BBFILE_PATTERN_secure-rpi := "^${LAYERDIR}/"
BBFILE_PRIORITY_secure-rpi = "6"

LAYERDEPENDS_secure-rpi = "core raspberrypi openembedded-layer security selinux"

LAYERSERIES_COMPAT_secure-rpi = "kirkstone"

WKS_SEARCH_PATH:append = " ${LAYERDIR}/wic"
