# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-networkconnection"
BBFILE_PATTERN_meta-networkconnection = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-networkconnection = "6"

LAYERDEPENDS_meta-networkconnection = "core"
LAYERSERIES_COMPAT_meta-networkconnection = "kirkstone"
